eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8085
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/

server:
  port: 8085

spring:
  application:
    name: zuul

zuul:
  routes:
    xuyang:
      path: /text/*
      serviceId: server01
    file:
      path: /file/*
      serviceId : fileServer